language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$AUTH_TOKEN"
  skip_cleanup: true
  on:
    branch: master
# after_success:
